# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: LEOçš„é˜æ¥¼
subtitle: LEO
description: è¦é™æ‚„æ‚„çš„å“¦ ğŸ¤«
keywords:
author: LEO
language: 
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.leo.red/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  hljs: true #æ–°å¢hljså‚æ•°ï¼Œå¹¶è®¾ä¸ºtryeï¼Œä¸ç„¶æ— æ³•ä½¿ç”¨highlight.js å®˜æ–¹çš„ css
  line_number: false #æš‚ä¸æ”¯æŒè¡Œå·
  auto_detect: false #è¿™ä¸€é¡¹ä¹Ÿå…³é—­ï¼Œè‹¥å¼€å¯æœ‰å¯èƒ½æŠ¥é”™
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: next
theme: cactus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@git.dev.tencent.com:zleo/leoBlog.git
  # repo: root@172.16.230.129:/var/repo/hexo.git
  # branch: master
  branch: coding-pages

# #å‹æƒ…é“¾æ¥
# friends:
#   - name: ä¹äºˆå¿˜å¿§
#     time: '2019-11-10'
#     url: 'https://www.laopaiyu.top/'
#     logo: 'https://www.laopaiyu.top/img/avatar.jpg'
#     intro: 'å‰ç«¯ç¬”è®°'
#   - name: æ‹½çˆ·
#     time: '2019-11-10'
#     url: 'https://zhuaiye.top/'
#     logo: 'https://zhuaiye.top/images/avatar.jpg'
#     intro: 'å’•å’•å’•'

# #è‡ªåŠ¨æœç´¢
# #https://github.com/alexbruno/hexo-generator-json-content
# jsonContent:
#   dateFormat: YYYY/MM/DD
#   pages: false
#   posts:
#     tags: true
#     title: true
#     date: true
#     text: true
#     permalink: true
#     photos: true
#   file: content.json

# #valineè¯„è®º
# valine:
#   API_ID: '9pTPrE5KsNXFmhNtj509wV8k-gzGzoHsz'
#   API_KEY: 'mMEqj1EFUiAeR2mPKpVr5mHr'

# #rss
# feed:
#   type: atom
#   path: atom.xml
#   limit: 20
#   hub:
#   content:
#   content_limit: 140
#   content_limit_delim: ''
#   order_by: -date
#   icon: icon.png
